version: '3.5'
services:
  fuseki:
    image: semapps/jena-fuseki-webacl:latest
    container_name: fuseki_aurba
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    networks:
      - semapps
    environment:
      ADMIN_PASSWORD: "admin"

  middleware:
    build: middleware
    container_name: middleware_aurba
    depends_on:
      - fuseki
    volumes:
      - ./middleware/:/app
      - ./data/fuseki/backups:/app/fuseki-backups # Needed to backup fuseki datasets
    environment:
      - SEMAPPS_SPARQL_ENDPOINT=http://fuseki_aurba:3030/
      - SEMAPPS_MAIN_DATASET=localData
      - SEMAPPS_JENA_USER=admin
      - SEMAPPS_JENA_PASSWORD=admin
      - SEMAPPS_INSTANCE_NAME="AUrba"
      - SEMAPPS_FRONT_URL="http://localhost:5000/"
      - SEMAPPS_HOME_URL=http://localhost:3000/
      - SEMAPPS_BACKUP_FUSEKI_DATASETS_PATH=/app/fuseki-backups
      - SEMAPPS_REDIS_CACHE_URL=redis://redis:6379/0
      - SEMAPPS_OIDC_ISSUER=https://login.lescommuns.org/auth/realms/master/
      - SEMAPPS_OIDC_CLIENT_ID=semapps
    ports:
      - "3000:3000"
    expose:
      - "3000"
    networks:
      - semapps
    command: bash -c "yarn install && pm2-runtime 'yarn run dev'"

  frontend:
    build: frontend
    container_name: frontend_aurba
    volumes:
      - ./frontend:/app
    environment:
      - REACT_APP_MIDDLEWARE_URL=http://localhost:3000/
      - PORT=5000
    depends_on:
      - middleware
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - semapps
    command: bash -c "yarn install && yarn start"

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - "6379"
    volumes:
      - ./data/redis_data:/data
    networks:
      - semapps
    command: ["redis-server", "--appendonly", "yes"]

networks:
  semapps:
    name: bus_network
    external: true
